package com.nonglam.open_server.shared;

public enum ErrorCode {
  POST_SPAM_DETECTED,
  POST_CONTENT_SPAM_DETECTED,
  POST_NOT_FOUND,
  REQUEST_SPAM_DETECTED,
  BAD_CREDENTIAL,
  OPENER_BLOCKED,
  EMAIL_EXISTS,
  USERNAME_EXISTS,
  TOO_MANY_REQUEST,
}
